"use client";

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { cn } from "@/lib/utils";
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Button } from '@/components/ui/button';
import { AGENTS, getAgentById, MeetingStrategy } from '@/lib/ai/agents';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { CheckSquare, Loader2, FileDown } from 'lucide-react';
import { createBrowserClient } from '@/lib/supabase/client';

interface MeetingHeaderProps {
  meetingId: string;
  title: string;
  strategy: MeetingStrategy;
  status: string;
  agents: Array<{ agent_id: string }>;
}

export function MeetingHeader({ meetingId, title, strategy, status, agents }: MeetingHeaderProps) {
  const router = useRouter();
  const [isEnding, setIsEnding] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const getStrategyLabel = (strategy: MeetingStrategy) => {
    const labels = {
      GROWTH: 'Growth Focused',
      SAFETY: 'Safety First',
      BALANCED: 'Balanced Approach',
    };
    return labels[strategy];
  };

  const getStrategyColor = (strategy: MeetingStrategy) => {
    const colors = {
      GROWTH: 'bg-green-100 text-green-800',
      SAFETY: 'bg-red-100 text-red-800',
      BALANCED: 'bg-blue-100 text-blue-800',
    };
    return colors[strategy];
  };

  const getInitials = (name: string) => {
    return name.split(' ').map(n => n[0]).join('').toUpperCase();
  };

  const getAgentColor = (color: string) => {
    const colors: Record<string, string> = {
      emerald: 'bg-emerald-500',
      blue: 'bg-blue-500',
      amber: 'bg-amber-500',
      pink: 'bg-pink-500',
      violet: 'bg-violet-500',
    };
    return colors[color] || 'bg-gray-500';
  };

  const handleEndMeeting = async () => {
    if (!confirm('Are you sure you want to end this meeting? This will generate a formal summary and decision record.')) return;
    
    setIsEnding(true);
    try {
      const response = await fetch(`/api/meetings/${meetingId}/end`, {
        method: 'POST',
      });
      
      if (!response.ok) throw new Error('Failed to end meeting');
      
      router.refresh();
    } catch (error) {
      console.error('Error ending meeting:', error);
      alert('Failed to end meeting. Please try again.');
    } finally {
      setIsEnding(false);
    }
  };

  const handleExportPDF = async () => {
    setIsExporting(true);
    try {
      const supabase = createBrowserClient();
      
      // Fetch memory
      const { data: memory, error } = await supabase
        .from('meeting_memories')
        .select('*')
        .eq('meeting_id', meetingId)
        .single();
        
      if (error || !memory) {
        alert('No official decision record found. Please ensure the meeting is ended correctly.');
        return;
      }

      // Dynamic import to avoid SSR issues
      const jsPDF = (await import('jspdf')).default;
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(22);
      doc.text('Board Meeting Decision Record', 20, 20);
      
      doc.setFontSize(12);
      doc.text(`Meeting: ${title}`, 20, 35);
      doc.text(`Date: ${new Date(memory.created_at).toLocaleDateString()}`, 20, 42);
      doc.text(`Strategy: ${strategy}`, 20, 49);
      
      // Line
      doc.setLineWidth(0.5);
      doc.line(20, 55, 190, 55);
      
      // Summary
      doc.setFontSize(16);
      doc.text('Executive Summary', 20, 70);
      doc.setFontSize(12);
      const summaryLines = doc.splitTextToSize(memory.summary, 170);
      doc.text(summaryLines, 20, 80);
      
      // Decision
      const decisionY = 80 + (summaryLines.length * 7) + 10;
      doc.setFontSize(16);
      doc.text('Final Decision & Recommendation', 20, decisionY);
      doc.setFontSize(12);
      const decisionLines = doc.splitTextToSize(memory.decision || 'No explicit decision recorded.', 170);
      doc.text(decisionLines, 20, decisionY + 10);
      
      // Footer
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text('Generated by VirtualBoard AI', 20, 280);
      
      doc.save(`Decision_Record_${title.replace(/\s+/g, '_')}.pdf`);
      
    } catch (e) {
      console.error(e);
      alert('Failed to export PDF');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Card className="p-4 border-0 rounded-none">
      <div className="flex items-center justify-between">
        <div className="space-y-1">
          <h1 className="text-2xl font-bold">{title}</h1>
          <div className="flex items-center gap-2">
            <Badge className={getStrategyColor(strategy)}>
              {getStrategyLabel(strategy)}
            </Badge>
            <Badge variant="outline">{status}</Badge>
          </div>
        </div>
        
        <div className="flex items-center gap-4">
          {status === 'ACTIVE' && (
            <Button 
              variant="default" 
              size="sm" 
              onClick={handleEndMeeting}
              disabled={isEnding}
            >
              {isEnding ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Finalizing...
                </>
              ) : (
                <>
                  <CheckSquare className="mr-2 h-4 w-4" />
                  End Meeting & Summarize
                </>
              )}
            </Button>
          )}

          {status === 'COMPLETED' && (
            <Button 
              variant="outline" 
              size="sm" 
              onClick={handleExportPDF}
              disabled={isExporting}
            >
              {isExporting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Exporting...
                </>
              ) : (
                <>
                  <FileDown className="mr-2 h-4 w-4" />
                  Export Decision Record
                </>
              )}
            </Button>
          )}

          <div className="text-right">
            <p className="text-sm text-muted-foreground">Active Advisors</p>
            <p className="text-sm font-medium">{agents.length} participants</p>
          </div>
          
          <div className="flex -space-x-2">
            {agents.map((agent, index) => {
              const agentData = getAgentById(agent.agent_id);
              if (!agentData) return null;
              
              return (
                <Avatar key={agent.agent_id} className="h-8 w-8 border-2 border-background">
                  <AvatarFallback className={cn(
                    'text-white text-xs',
                    getAgentColor(agentData.color)
                  )}>
                    {getInitials(agentData.name)}
                  </AvatarFallback>
                </Avatar>
              );
            })}
          </div>
        </div>
      </div>
      
      <Separator className="my-4" />
      
      <div className="flex items-center justify-between text-sm text-muted-foreground">
        <p>Virtual Board Meeting in Progress</p>
        <p>Strategy: {strategy} | Participants: {agents.length}</p>
      </div>
    </Card>
  );
}